[phases.build]
cmds = [
    "echo 'Building PHP application for Railway...'",
    "php --version",
    "ls -la"
]

[phases.start]
cmd = "php -S 0.0.0.0:$PORT router.php"

[variables]
PHP_VERSION = "8.2"
