[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t ."
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[variables]
PHP_VERSION = "8.2"
NIXPACKS_PHP_ROOT_DIR = "."
